osx_image: xcode9
xcode_project: MacPassHTTP.xcodeproj
xcode_scheme: MacPassHTTP
language: objective-c

before_install:
  # get MacPass sources
  - git clone --recursive --depth=50 --branch=continuous https://github.com/mstarke/MacPass.git "${TRAVIS_BUILD_DIR}/../MacPass"
  - cd "${TRAVIS_BUILD_DIR}/../MacPass"
  - carthage bootstrap --platform Mac
  - cd "{TRAVIS_BUILD_DIR}"
  - carthage bootstrap --platform Mac # run carthage for MacPassHTTP

after_success:
  - cd ./build/Build/Products/Release
  - zip -9r MacPassHTTP-continuous.zip MacPassHTTP.mpplugin
  - cd -
  - mv ./build/Build/Products/Release/MacPassHTTP-continuous.zip .

script: xcodebuild clean && xcodebuild build -configuration release -project MacPassHTTP.xcodeproj  -scheme MacPassHTTP CODE_SIGNING_REQUIRED=NO -derivedDataPath ./build

# branches:
#   only:
#     - /^(?i:continuous)$/
